name: diet_track
publish_to: 'none' 
version: 0.0.3+15

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  get: ^4.6.5
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  email_validator: ^2.1.17
  intl: ^0.17.0
  firebase_crashlytics: ^3.0.16
  flutter_native_splash: ^2.2.19
  image_picker: ^0.8.7+1
  hive: ^2.2.3
  firebase_storage: ^11.1.0
  uuid: ^3.0.7
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  adaptive_theme: ^3.2.1
  dio: ^5.2.1+1

  #dart run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
  http: ^1.1.0

dev_dependencies:
  #dart run build_runner build
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
     - family: SF-Pro-Rounded
       fonts:
         - asset: assets/fonts/SF-Pro-Rounded-Light.otf
           weight: 300
         - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
           weight: 400
         - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
           weight: 500
         - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
           weight: 600
         - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
           weight: 700

flutter_launcher_icons:
  image_path_android: "assets/images/app_icon.png"
  android: true 
  min_sdk_android: 21